version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: build
          command: |
            cd src
            ls

            echo 1.0.$CIRCLE_BUILD_NUM >> version
            cat version

            APP_VERSION=$(cat version)
            echo $APP_VERSION

            dotnet restore --packages packages
            dotnet build --no-restore --configuration Release /p:Version=${APP_VERSION}
            dotnet pack --no-build --no-restore --configuration Release --output ../nupkgs /p:Version=${APP_VERSION}
      - persist_to_workspace:
          root: .
          paths:
            - src/nupkgs
            - src/version
  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - attach_workspace:
          at: ./
      - run: |
          pwd
          
          cd src
          APP_VERSION=$(cat version)
          echo $APP_VERSION
          cd ..

          cd nupkgs
          ls
          nuget push Core.${APP_VERSION}.nupkg $nuget-api -Source https://www.myget.org/F/simple-shop/api/v2/package
          
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          context: build-ctx
          requires:
            - build