version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: build
          command: |
            cd src
            ls

            echo 1.0.$CIRCLE_BUILD_NUM >> version
            cat version

            APP_VERSION=$(cat version)
            echo $APP_VERSION

            dotnet restore
            dotnet msbuild /target:Build /p:Configuration=Release /p:Version=${APP_VERSION}

            mkdir ./nupkgs
            mv **/bin/**/*.nupkg ./nupkgs

            cd nupkgs
            pwd
            ls
      - persist_to_workspace:
          root: .
          paths:
            - src/nupkgs
            - src/version
  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - attach_workspace:
          at: ./
      - run: |
          pwd
          cd src
          cd nupkgs

          rm *.symbols.nupkg
          ls
          
          dotnet nuget push *.nupkg -k ${nugetapi} -s https://www.myget.org/F/simple-shop/api/v3/index.json

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          context: build-ctx
          requires:
            - build